// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTelemetry() {
  return window['go']['main']['App']['GetTelemetry']();
}

export function SetFanSpeed(arg1) {
  return window['go']['main']['App']['SetFanSpeed'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function SetPower(arg1) {
  return window['go']['main']['App']['SetPower'](arg1);
}
