// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTelemetry():Promise<string>;

export function SetFanSpeed(arg1:number):Promise<void>;

export function SetMode(arg1:number):Promise<void>;

export function SetPower(arg1:boolean):Promise<void>;
